const DEFAULT_CONFIDENCE = 90;
const DEFAULT_DECAY = 0;
const LOWER_CONFIDENCE_LIMIT = 40;
const DEFAULT_POLLING_RATE_MS = 1000;

export {
  DEFAULT_CONFIDENCE,
  DEFAULT_DECAY,
  LOWER_CONFIDENCE_LIMIT,
  DEFAULT_POLLING_RATE_MS,
};
